Traceback (most recent call last):
  File "/Users/nce8/miniforge3/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/nce8/miniforge3/lib/python3.12/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nce8/miniforge3/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nce8/miniforge3/lib/python3.12/asyncio/base_events.py", line 686, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/nce8/miniforge3/lib/python3.12/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/Users/nce8/miniforge3/lib/python3.12/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/nce8/miniforge3/lib/python3.12/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import altair as alt
import altair_saver
import pandas as pd
data = pd.read_csv("neg_anscombes.csv")
for i in range(1, 5):
    c = (alt.Chart(data).mark_point()
    .encode(
        x=alt.X(f"x_{i}", scale=alt.Scale(zero=False)),
        y=alt.Y(f"y_{i}", scale=alt.Scale(zero=False))
    ))
    fit = c.transform_regression(
        f"y_{i}", f"x_{i}"
    ).mark_line()
    o = fit + c
    o.show()
    altair_saver.save(o, f"../images/anscombes_{i}.png")
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[1], line 2[0m
[1;32m      1[0m [38;5;28;01mimport[39;00m [38;5;21;01maltair[39;00m [38;5;28;01mas[39;00m [38;5;21;01malt[39;00m
[0;32m----> 2[0m [38;5;28;01mimport[39;00m [38;5;21;01maltair_saver[39;00m
[1;32m      3[0m [38;5;28;01mimport[39;00m [38;5;21;01mpandas[39;00m [38;5;28;01mas[39;00m [38;5;21;01mpd[39;00m
[1;32m      4[0m data [38;5;241m=[39m pd[38;5;241m.[39mread_csv([38;5;124m"[39m[38;5;124mneg_anscombes.csv[39m[38;5;124m"[39m)

[0;31mModuleNotFoundError[0m: No module named 'altair_saver'

